feat: new p2tr_ns payment for tapscript n-of-n scripts
BitGo/bitcoinjs-lib pull request #19
Opened 2021-11-01 18:54 UTC by brandonblack

* Input won't match unsigned witness tack to avoid colliding with
traditional m-of-n scripts

Co-authoried-by: Daniel McNally <danielmcnally@bitgo.com>

2021-11-01 20:57 UTC, sangaman approved these changes
Looks good, I've found the p2tr_ns payment type has been really handy to have opposed to manually crafting the scripts. I made a handful of minor suggestions to consider.

2021-11-01 20:57 UTC, sangaman commented on test/payments.spec.ts
> -['embed', 'p2ms', 'p2pk', 'p2pkh', 'p2sh', 'p2tr', 'p2wpkh', 'p2wsh'].forEach(
This file looks like mostly (all?) formatting changes due to adding a payment type which caused indentation to shift.

2021-11-01 20:57 UTC, sangaman commented on ts_src/classify.ts
> +  P2TR: 'taproot' as string,
I never understood why this is casting a string to a string.

2021-11-01 20:57 UTC, sangaman commented on ts_src/payments/p2tr_ns.ts
> +      o.n = a.pubkeys.length;
Any thoughts on requiring `length > 1` here?

2021-11-01 20:57 UTC, sangaman commented on ts_src/payments/p2tr_ns.ts
> +    chunks = bscript.decompile(output) as Stack;
I could maybe see some value in having `chunks` and `decodedChunks` or something along those lines just so they're never confused for each other. Otherwise can keep the same pattern with the `decoded` flag, or maybe even just do  `if (decodedChunks) return;` here.

2021-11-01 20:57 UTC, sangaman commented on ts_src/payments/p2tr_ns.ts
> +    o.pubkeys = chunks.filter((_, index) => index % 2 === 0) as Buffer[];
Does it make sense for this line to be within the lazy `pubkeys` function? It's already calling `decode` from within there.

2021-11-01 20:57 UTC, sangaman commented on ts_src/payments/p2tr_ns.ts
> +        throw new TypeError('Input has invalid signature(s)');
Maybe a `missing signatures` error for the case when `length` is 0? Or you could just ignore the empty array case here and let it get handled below with the signature count mismatch error.

2021-11-01 20:57 UTC, sangaman commented on ts_src/templates/taprootnofn/input.ts
> +function partialSignature(value: number | Buffer): boolean {
`isPartialSignature`?

2021-11-01 20:57 UTC, brandonblack commented on test/payments.spec.ts
> -['embed', 'p2ms', 'p2pk', 'p2pkh', 'p2sh', 'p2tr', 'p2wpkh', 'p2wsh'].forEach(
Yes :hate:

2021-11-01 20:58 UTC, brandonblack commented on ts_src/classify.ts
> +  P2TR: 'taproot' as string,
Yeah, no idea, but I'm a sucker for maintaining patterns.

2021-11-01 21:00 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +      o.n = a.pubkeys.length;
I think we should be checking `>= 1` actually. 1 is fine, and produces a meaningful script (if in a slightly odd way to use the thing).

2021-11-01 21:12 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +    o.pubkeys = chunks.filter((_, index) => index % 2 === 0) as Buffer[];
Yeah, that could use some refactor.

2021-11-01 21:15 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +    chunks = bscript.decompile(output) as Stack;
Yeah, should have been a `lazy()`

2021-11-01 21:47 UTC, sangaman approved these changes

2021-11-01 21:54 UTC, tylerlevine requested changes
minor comments, this is looking really great

2021-11-01 21:54 UTC, tylerlevine commented on ts_src/classify.ts
> +  P2TR: 'taproot' as string,
I think otherwise the type is `'taproot'` (constant string). Maybe we're using it somewhere that can't handle that type?

2021-11-01 21:54 UTC, tylerlevine commented on ts_src/templates/taprootnofn/output.ts
> +// m [pubKeys ...] n OP_CHECKMULTISIG
I think comment is incorrect here, should be `[pubKey] OP_CHECKSIGVERIFY ... [pubKey] OP_CHECKSIG`?

2021-11-01 21:54 UTC, tylerlevine commented on ts_src/payments/p2tr_ns.ts
> +    );
optional nit to avoid casts:
```suggestion
    if (Buffer.isBuffer(x)) {
      return bscript.isCanonicalSchnorrSignature(x);
    }
    return !!opts?.allowIncomplete ? x === OPS.OP_0 : false;
    );
```

I think there might also be some subtle logic issues here, eg (`allowIncomplete: false` and `x === OPS.OP_0`) would return true since `false !== undefined`.

2021-11-01 21:54 UTC, tylerlevine commented on ts_src/payments/p2tr_ns.ts
> +        throw new TypeError('Output is invalid');
would it make sense to throw a more descriptive error here? I guess we could always check the line in the stack trace to know which case failed.

2021-11-02 14:10 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +    );
Using a slightly tweaked version of this, thanks!

2021-11-02 14:10 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +        throw new TypeError('Output is invalid');
Sure, I'll upgrade all those error messages.

2021-11-02 14:11 UTC, brandonblack commented on ts_src/templates/taprootnofn/output.ts
> +// m [pubKeys ...] n OP_CHECKMULTISIG
Fixing that one and the corresponding `input.ts` one. Nice.

2021-11-02 14:11 UTC, brandonblack commented on ts_src/classify.ts
> +  P2TR: 'taproot' as string,
Thanks for the knowledge!

2021-11-02 14:26 UTC, OttoAllmendinger reviewed
two style nits

2021-11-02 14:29 UTC, brandonblack commented on ts_src/payments/p2tr_ns.ts
> +          i !== pks.length - 1 ? OPS.OP_CHECKSIGVERIFY : OPS.OP_CHECKSIG,
I had liked the aesthetic of putting the opcode that actually goes last last, but totally understand the clarity issue. That's two votes (you and Underwood) for changing it.

2021-11-02 15:44 UTC, tylerlevine approved these changes

2021-11-02 15:44 UTC, merged