Full 64 bit number support for tx outputs
BitGo/bitcoinjs-lib pull request #36
Opened 2022-07-11 16:47 UTC by williamqin-bitgo

Update bufferutils and satoshi type to support bigint
Add TNumber generic to tx, txb, block

Add tests to `bufferutils` and `transaction_builder`

https://bitgoinc.atlassian.net/browse/BG-51990

2022-07-12 08:48 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
>  }
This can be simplified. Adding commits to this PR.

2022-07-12 09:21 UTC, OttoAllmendinger commented on test/transaction_builder_bigint.spec.ts
> +import * as assert from 'assert';
I sketched the start of solution here: https://github.com/BitGo/bitcoinjs-lib/pull/36/commits/a9cfeadbad4ad77a3dfcab31e226a86ccff17a44

you should be able to extend it so that it covers the more interesting `bigint` paths

2022-07-12 12:44 UTC, williamqin-bitgo commented on ts_src/bufferutils.ts
>  }
Didn't know there was `buffer.writeBigUInt64LE` and `buffer.readBigUInt64LE`!

2022-07-14 18:14 UTC, williamqin-bitgo commented
`transaction_builder_bigint.json` tests are a copy of `transaction_builder.json` except all outputs are greater than `Number.MAX_SAFE_INTEGER` and also have `output != Number(output)` (i.e. they are unsafe)

Extra care was taken in writing the `multisig` tests, including manually inspecting the differing `scriptSig`

Aside from that, this PR is now ready for review. Will squash commits after approval/before merging.

2022-07-15 00:59 UTC, williamqin-bitgo commented on src/transaction_builder.js
> +        a + (typeof x.value !== 'undefined' ? BigInt(x.value) : BigInt(0)),
I believe this code used to cast `undefined` to `0`, so it's being replicated in the new code

2022-07-15 01:06 UTC, williamqin-bitgo commented on src/transaction_builder.js
> +        a + (typeof x.value !== 'undefined' ? BigInt(x.value) : BigInt(0)),
Also note the comment on the previous line
`// not all inputs will have .value defined`

2022-07-18 22:29 UTC, tylerlevine requested changes
small things I found but please take a look. Other than that lgtm. Nice work 👍

2022-07-18 22:29 UTC, tylerlevine commented on ts_src/transaction_builder.ts
> +  witnessValue?: TNumber;
Does doge support segwit? If not, does this need to be changed?

2022-07-18 22:29 UTC, tylerlevine commented on ts_src/transaction_builder.ts
> +    const feeRate = fee / BigInt(bytes);
I think we should assume that the `fee` (ie, the difference between the input amount and output amount) is representable by a `number`, otherwise we can't properly handle non-integer `feeRate` here since `BigInt` always rounds down. Open to your thoughts on this.
```suggestion
    const feeRate = Number(fee) / bytes;
```

2022-07-19 13:22 UTC, williamqin-bitgo commented on ts_src/transaction_builder.ts
> +  witnessValue?: TNumber;
segwit is planned for the next major release https://github.com/dogecoin/dogecoin/discussions/2264
but currently, doge does not support segwit

2022-07-20 17:50 UTC, tylerlevine approved these changes

2022-07-20 17:51 UTC, merged