fix: don't use buffer.readBigUInt64LE in number path
BitGo/bitcoinjs-lib pull request #37
Opened 2022-08-12 00:48 UTC by williamqin-bitgo

BG-54862

2022-08-12 01:40 UTC, williamqin-bitgo commented
Some adhoc tests to verify `buffer.readBigUInt64LE` and `buffer.writeBigUInt64LE` have been removed from the `number` path
<img width="1475" alt="image (1)" src="https://user-images.githubusercontent.com/104778060/184269537-68c1f6d2-886c-48a5-ac23-226b583b3769.png">

<img width="1544" alt="image (2)" src="https://user-images.githubusercontent.com/104778060/184269553-99527ef3-b2f1-4ed8-9c8f-97755191feff.png">

2022-08-12 01:42 UTC, williamqin-bitgo commented
<img width="1563" alt="image (3)" src="https://user-images.githubusercontent.com/104778060/184269757-2d4c376d-bef8-4693-9f09-bc17bdc2829a.png">

2022-08-12 14:18 UTC, OttoAllmendinger requested changes

2022-08-12 14:18 UTC, OttoAllmendinger commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
this will likely cause the same error since the method is missing in our Buffer polyfill

2022-08-12 14:18 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
see other comment

2022-08-12 14:37 UTC, williamqin-bitgo commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
I don't think so, it should only error when the method is called, as the code red was a runtime error.

2022-08-12 14:39 UTC, OttoAllmendinger commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
right, it will error for `value === 'bigint'` though (which we are trying to make use of soon)

2022-08-12 14:42 UTC, williamqin-bitgo commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
ah, we could either change to use 32bit buffer funcs only or update the polyfill
in any case, it will only be an issue for doge unlike the code red where it was for all utxo

2022-08-12 14:47 UTC, OttoAllmendinger commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
I don't think we want to maintain the third-party polyfill so let's better work on a solution using 32bit API.

You are correct, it will only be an issue for doge, but one we have to fix nonetheless. We need to add a FIXME here at least.

2022-08-12 14:47 UTC, williamqin-bitgo commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
sounds good, will update pr to use 32 bits only

2022-08-12 15:11 UTC, williamqin-bitgo commented on src/bufferutils.js
> +    buffer.writeBigUInt64LE(BigInt(value), offset);
updated :)

2022-08-12 15:13 UTC, williamqin-bitgo commented
adhoc tests above are now actually integrated into the tests

2022-08-12 15:24 UTC, OttoAllmendinger requested changes

2022-08-12 15:24 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> +    const dividend = (value - remainder) / mask;
I don't think this is the correct terminology. A "dividend" refers to the number that gets divided, but in this case here it is the result of a division. How about `const lower32Bits` and `const upper32Bits`  ?

2022-08-12 15:24 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> +  return b + a;
you can revert this change

2022-08-12 15:24 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> -  buffer.writeBigUInt64LE(BigInt(value), offset);
you could `value = BigInt(value)` here and inline the `typeof value = 'bigint'` branch again

2022-08-12 15:52 UTC, williamqin-bitgo commented on ts_src/bufferutils.ts
> +    const dividend = (value - remainder) / mask;
oops, bad terminology, mixed up `dividend` with `quotient` 😢

2022-08-12 15:52 UTC, williamqin-bitgo commented on ts_src/bufferutils.ts
> +  return b + a;
would it be good to revert back to the original implementation (this change) for less risk?

2022-08-12 15:54 UTC, williamqin-bitgo commented on ts_src/bufferutils.ts
> -  buffer.writeBigUInt64LE(BigInt(value), offset);
same concern as above, we would be changing the `number` code path

2022-08-12 16:50 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> +  return b + a;
I guess it depends on how confident you are that this implementation is correct ;-)

2022-08-12 16:52 UTC, OttoAllmendinger approved these changes
IMO using the same paths for `number` and `bigint` would work, but we will hopefully go back to using `writeUInt64` anyway once we figure out the polyfill problem

2022-08-16 20:36 UTC, tylerlevine approved these changes

2022-08-16 20:36 UTC, tylerlevine commented on ts_src/bufferutils.ts
> +  verifuint(b + a, 0x001fffffffffffff);
nit: Use `Number.MAX_SAFE_INTEGER` here for readability.

2022-08-16 20:36 UTC, tylerlevine commented on ts_src/bufferutils.ts
> +    buffer.writeUInt32LE(Number(BigInt.asUintN(32, upper32bits)), offset + 4);
nit: seems a bit odd to be using the math functions here instead of bit shifting, but it's not incorrect

2022-08-16 20:37 UTC, tylerlevine commented
I'm not sure why the tests from the screenshots were removed but hopefully we can add them back once at a later time.

2022-08-16 20:38 UTC, merged

2022-08-16 20:53 UTC, williamqin-bitgo commented
> I'm not sure why the tests from the screenshots were removed but hopefully we can add them back at a later time.


They were actually added! https://github.com/BitGo/bitcoinjs-lib/blob/4ad5831d3b7836011d46703f4dc53d47833ae93d/test/bufferutils.spec.ts#L10

2022-08-17 06:03 UTC, OttoAllmendinger commented on ts_src/bufferutils.ts
> +  verifuint(b + a, 0x001fffffffffffff);
this is a common bitcoinjs-lib-ism