feat: add initial p2tr output script support
BitGo/bitcoinjs-lib pull request #8
Opened 2021-09-22 21:24 UTC by sangaman

This introduces support for creating p2tr output scripts and addresses from one or more pubkeys and/or one or more scripts according to BIPs 340 & 341.

Multiple pubkeys are aggregated according to the procedure defined by MuSig whereby all keys are concatenated and hashed, with the resulting hash multiplied against each pubkey to tweak it. These tweaked pub keys are added together to produce the internal pubkey. If only one pubkey is provided, then the internal pubkey is simply set to that. And if no pubkeys are provided, a key with no known secret key is used instead.

Any scripts provided are arranged into a Huffman tree according to their weighted probability and then hashed to form a merkle tree. The root hash of this tree is then added to the internal pubkey to tweak it. This tweaked key is finally used for creating the output script which is then encoded using Bech32m.

Test cases in this commit include examples from the Bitcoin Optech taproot workshop that derive a Bech32m address from scripts and an internal key.

Follow-ups to this commit should include expanding the coverage and number of test cases as well as possibly restructuring existing code or moving logic to other packages/modules. We should also consider support for taproot output descriptors, which are currently under review and development in Bitcoin Core.

Ticket: BG-35571

2021-09-22 22:26 UTC, brandonblack commented on ts_src/taproot.ts
> +  });
```suggestion
const trimmedPubkeys = pubkeys.map(trimFirstByte).sort();
```
I _think_ the byte we're trimming could effect sort order, but maybe not if bitcoin always uses the odd|even pubkey. Either way, this is cleaner IMO.

2021-09-22 22:26 UTC, brandonblack commented on ts_src/taproot.ts
> +  });
```suggestion
const tweakedPubkeys = pubkeys .map((pubkey) => {
  const trimmedPubkey = trimFirstByte(pubkey);
  const c = bcrypto.sha256(Buffer.concat([L, trimmedPubkey]));
  return ecc.pointMultiply(pubkey, c);
})
const aggregatePubkey = tweakedPubkeys.slice(1).reduce(ecc.pointAdd, tweakedPubkeys[0]);
```
Alternate construction - kinda two separate ideas:
1) make tweaking and combining the pubkeys separate, because this helps show that order doesn't matter
2) use a slightly clever `reduce` construction to eliminate the ugly conditional

2021-09-22 22:26 UTC, brandonblack commented on ts_src/taproot.ts
> +    // If the spending conditions do not require a script path, the output key should commit to an
Can you link me to the explanation of this?

2021-09-22 22:26 UTC, brandonblack commented on ts_src/taproot.ts
> +
nit: Might be nicer to shrink the conditional block by doing `let tapTweak;` at the top, and then doing the `pointAddScalar` right before return.

2021-09-22 22:26 UTC, brandonblack commented on ts_src/taproot.ts
> +export function getHuffmanTaptreeRoot(
This function is a tiny bit hard to reason about, but I love it.

2021-09-23 01:55 UTC, sangaman commented on ts_src/taproot.ts
> +  });
Very good point, this ought to be sorting only on the 32 byte x coordinate, ignoring any leading `0x02`/`0x03` byte. Plus this is just more succinct.

2021-09-23 02:24 UTC, sangaman commented on ts_src/taproot.ts
> +  });
I like it. Needed to tweak this slightly though, the suggested code strangely caused the tests to fail. Turns out that `pointAdd` takes a third parameter indicating whether the key is compressed or not, if falsey it returns a 65 byte uncompressed key instead of the 33 byte compressed key. The third parameter for `reduce` is the current index so for index `0`, `pointAdd` treats that as false and returns a 65 byte key and messes the whole thing up. Got it to work with `reduce((prev, curr) => ecc.pointAdd(prev, curr), tweakedPubkeys[0]);`. Had me questioning my sanity briefly though.

2021-09-23 02:26 UTC, sangaman commented on ts_src/taproot.ts
> +    // If the spending conditions do not require a script path, the output key should commit to an
https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#cite_note-22 - I'll add this to the comments.

2021-09-23 02:34 UTC, sangaman commented on ts_src/taproot.ts
> +export function getHuffmanTaptreeRoot(
Yep I struggled a bit with how to frame/structure this. It does quite a bit, but I also figure we'll need more from this construction eventually because we need to preserve knowledge of the internal hashes of the tree to be able to spend using scripts. For now it just constructs the tree and gives us the root hash, which is all we need for creating the output script. I'll go through this again and add some comments, but it will need to be reworked eventually either way I'm pretty sure.

2021-09-23 04:03 UTC, tylerlevine requested changes
excellent work - this is a really great PR here!

No major blockers but I think some additional test cases that cross reference test vectors from other p2tr or musig2 key aggregation implementations would be useful.

2021-09-23 04:03 UTC, tylerlevine commented on ts_src/taproot.ts
> +export function getHuffmanTaptreeRoot(
Yes I find it quite nice too - some more comments might be useful though, especially around the reasoning on why the non-null assertions are safe (which I believe them to be).

2021-09-23 04:09 UTC, tylerlevine commented
also please check the failing lint step - just looks like the imports need to be ordered

2021-09-23 04:24 UTC, sangaman commented on test/fixtures/p2tr.json
> +{
The first two cases are from the optech taproot workshop (specifically section 2.4). The first one is basically lifted straight from one of their examples - it uses the same internal pubkey but the scripts are generated from random keys (1 per script). For the second one I tweaked the python code to create an aggregated pubkey from 2 of the 3 keys, and tweaked the scripts to be 2 of 2 multisigs using `OP_CHECKSIGVERIFY` (not that the correctness of the scripts matters per se, but I was trying to approximate the BitGo multisig use case). In both cases I'm checking that we get the same outputs as with the optech workshop code.

The second two are just taken from scripts/addresses I randomly generated with Bitcoin Core using https://github.com/bitcoin/bitcoin/pull/22364 - just double-checking the output script to address functionality.

2021-09-23 04:26 UTC, sangaman commented on test/taproot.spec.ts
> +import { describe, it } from 'mocha';
Indeed, this was a copy-paste job from another test suite. Looks like a lot of the existing ones import this unnecessarily, fwiw.

2021-09-23 04:30 UTC, sangaman commented on test/taproot.spec.ts
> +export const OPS = require('bitcoin-ops') as { [index: string]: number };
This was another copy-paste job, exporting is totally unnecessary here. Trying to import and use types here instead of `require`ing results in `This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag` so I won't bother it.

Since I'm only using it once in this spec file, and the specific op code isn't particularly important to the test, I'll just use the raw value and add a comment.

2021-09-23 04:36 UTC, sangaman commented on test/taproot.spec.ts
> +  it('aggregates pubkeys', () => {
I'll give that a shot as I agree more thorough test cases are needed. I did look there but couldn't come up with anything I could just grab and use here for the output side of things only. Running tests w/ debug statements could work tho at least for the aggregated key side of things, I'd still want more coverage for taptree creation and key tweaking.

2021-09-23 04:39 UTC, sangaman commented on ts_src/payments/p2tr.ts
> +const H = Buffer.from(
I've updated the comment for this variable with some more detail about how this value is derived. I went with `H` because that's what used in BIP341 to describe this variable. Personally I think it's OK since it's only used in one place and that has comments for what it's for, along with the comments for the variable here. I think unless you're familiar with that section of BIP341 even a more descriptive name like `UNKNOWN_DLOG_INTERNAL_KEY` will be unclear without context.

2021-09-23 04:40 UTC, sangaman commented on ts_src/taproot.ts
> +// const SECP256K1_ORDER = Buffer.from('fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141', 'hex')
Yeah, I was originally going to use this for manually negating keys but I don't think that's necessary here.

2021-09-23 04:44 UTC, sangaman commented on ts_src/taproot.ts
> +  // µ_i = H(L || i)
You're absolutely right... I actually copied this line (since there's no µ key on my keyboard) from the musig readme in secp256k1-zkp here https://github.com/ElementsProject/secp256k1-zkp/blob/master/src/modules/musig/musig.md. It's probably worth fixing there as well, you can do the honors if you'd like since you found the mistake.

2021-09-23 04:49 UTC, sangaman commented on ts_src/taproot.ts
> +  // TODO: use multiple byte `size` when script length is >= 253 bytes
Yeah that's a good idea. Alternatively I will revisit this inside this PR and just implement the correct logic for larger lengths, it just wasn't particularly easy to do at first pass and I didn't want to get bogged down on it. At least not without introducing a new dependency on something like https://www.npmjs.com/package/structjs.

Here's the reference logic from the optech workshop, fyi:

```python
def ser_compact_size(l):
    r = b""
    if l < 253:
        r = struct.pack("B", l)
    elif l < 0x10000:
        r = struct.pack("<BH", 253, l)
    elif l < 0x100000000:
        r = struct.pack("<BI", 254, l)
    else:
        r = struct.pack("<BQ", 255, l)
    return r
```

2021-09-23 04:53 UTC, sangaman commented on ts_src/taproot.ts
> +  );
I'm a fan.

2021-09-23 04:55 UTC, sangaman commented on ts_src/taproot.ts
> +    const weight = weights ? weights[index] || 1 : 1;
I tried exactly this but the compiler would not accept it. I honestly wasn't sure if it was due to an older version of typescript or if doing `?.[]` is just invalid, so I went with what's there currently.

2021-09-23 05:36 UTC, sangaman commented on ts_src/taproot.ts
> +    // If the spending conditions do not require a script path, the output key should commit to an
Looking at this again I was definitely missing the `hashTapTweak` tagged hash part. I *believe* though that the multiplication by the generator gets handled within the `pointAddScalar` function, although I may be wrong. I wouldn't be sure how to do it otherwise. Getting my hands on a test case would be ideal, as I could pin down this logic pretty easily with that. No luck so far though.

2021-09-23 05:45 UTC, sangaman commented
@tylerlevine @brandonblack Thanks for the feedback. I was able to address most of the comments. There are still just a couple of loose ends plus I'd still like to add more tests if possible before wrapping this up.

2021-09-23 08:17 UTC, OttoAllmendinger requested changes
let's add some test vectors:

https://raw.githubusercontent.com/bitcoin-core/qa-assets/main/unit_test_data/script_assets_test.json

(usage:
https://github.com/bitcoin/bitcoin/blob/3820090bd619ac85ab35eff376c03136fe4a9f04/src/test/script_tests.cpp#L1718)

2021-09-23 08:17 UTC, OttoAllmendinger commented on ts_src/taproot.ts
> +export function aggregateMuSigPubkeys(pubkeys: Buffer[]): Buffer {
assert length > 0 (or maybe > 1 even?)

2021-09-23 08:17 UTC, OttoAllmendinger commented on ts_src/taproot.ts
> +  // TODO: use multiple byte `size` when script length is >= 253 bytes
`varunit-bitcoin` https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/package.json#L65

2021-09-23 08:17 UTC, OttoAllmendinger commented on types/payments/index.d.ts
> +    weights?: number[];
for the p2sh payments for instance, the construction happens via the `output` or `redeem` property: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/ts_src/payments/p2sh.ts#L91-L94

maybe we should declare `output?: Buffer | Buffer[]` / `redeem?: Payment | Payment[]` instead here to stay consistent

2021-09-23 12:56 UTC, sangaman commented on ts_src/taproot.ts
> +    // If the spending conditions do not require a script path, the output key should commit to an
Following up on this the way I currently have it with the taptweak tagged hash makes sense to me at least. We're tweaking the internal pubkey with a tagged hash just like we do when we have an actual script path, thus not leaking that there is no script path, but we're doing it with something that can't be used for script spending.

2021-09-23 13:11 UTC, sangaman commented on ts_src/payments/p2tr.ts
> + * This is equal to SHA256(uncompressedDER(SECP256K1_GENERATOR_POINT)).
Yes I was aware of this and meant to revisit it to at least put a TODO here. My main concern was what to do with the randomly generated integer after using it. If we just discard it then we can't prove an unspendable key path, which might be acceptable. Alternatively I could add it as a field on the `Payment` object - that might make the most sense. What do you think?

2021-09-23 13:13 UTC, sangaman commented on ts_src/taproot.ts
> +export function aggregateMuSigPubkeys(pubkeys: Buffer[]): Buffer {
Yes, I think > 1 makes most sense actually.

2021-09-23 14:14 UTC, sangaman commented on ts_src/payments/p2tr.ts
> + * This is equal to SHA256(uncompressedDER(SECP256K1_GENERATOR_POINT)).
Oh and the reason I didn't perform the hash here is just because the value is provided explicitly in the BIP. I suppose I could actually perform the hash but I figured a clear comment explaining how it was derived is just as good.

2021-09-23 14:34 UTC, OttoAllmendinger commented on ts_src/payments/p2tr.ts
> + * This is equal to SHA256(uncompressedDER(SECP256K1_GENERATOR_POINT)).
let's keep the hardcoded value and link to the BIP with a TODO

adding more stuff to `Payment` should be avoided if possible

2021-09-23 15:26 UTC, sangaman commented on ts_src/taproot.ts
> +  // TODO: use multiple byte `size` when script length is >= 253 bytes
Thanks otto, that looks like just what I need. I'm going to split this logic into its own function and add some test cases.

2021-09-23 18:31 UTC, sangaman commented on types/payments/index.d.ts
> +    weights?: number[];
I see how we'd (eventually) want to construct output from redeem, but I'm a bit confused by what you mean here. Why could `output` be `Buffer[]`? Wouldn't it always be the 34 byte locking script?

2021-09-23 19:09 UTC, Xekyo commented
I guess that you are aware of this, but I just wanted to point out that the Optech Taproot Workshop was published in October 2019, and the latest changes to the Taproot specification were made in August 2020. This may mean that the content of the workshop doesn't necessarily reflect the latest specification. I haven't reviewed the changes here, I just saw in a commit message that examples from the workshop were used, so I thought I'd point it out in case it was not known.

2021-09-23 20:36 UTC, brandonblack commented on ts_src/taproot.ts
> +    const c = bcrypto.sha256(Buffer.concat([L, trimmedPubkey]));
Did you see https://github.com/ElementsProject/secp256k1-zkp/blob/881b15cb4371d4b58d851575f2eb1832e0dfd5b2/src/modules/musig/musig-spec.mediawiki?
It looks like secp256k1-zkp is going to implement key aggregation based on MuSig2* instead of MuSig2, which would mean using `1` for the exponent of the second key in the sorted list, which would complicate everything here.

2021-09-23 23:12 UTC, sangaman commented on ts_src/taproot.ts
> +    const c = bcrypto.sha256(Buffer.concat([L, trimmedPubkey]));
Thank you, I did not see this. I'd read elsewhere that the key aggregation routine for MuSig1 was the same as MuSig2, but I wasn't aware of MuSig2*. It's easy enough to implement that logic here, just add this special case for the second element, but I'm not sure how that affects the tests and signing procedure. BIP340 doesn't mention it (it doesn't mention MuSig2 at all). I'm inclined to just leave this alone in this PR but keep it in mind and revisit when we have some signing logic to work with and a better idea of the implications.

2021-09-23 23:17 UTC, sangaman commented
> I guess that you are aware of this, but I just wanted to point out that the Optech Taproot Workshop was published in October 2019, and the latest changes to the Taproot specification were made in August 2020. This may mean that the content of the workshop doesn't necessarily reflect the latest specification. I haven't reviewed the changes here, I just saw in a commit message that examples from the workshop were used, so I thought I'd point it out in case it was not known.

Thanks, I was aware that the optech workshop is older than the latest changes to the BIPs, but as far as I could tell the examples from the workshop I referenced were in accordance with BIPs 340/341 and the code accompanying them. There have been ongoing updates to the github repo for the optech examples since they were published, so that may be why there weren't any discrepancies I could detect. Still something to keep in mind.

2021-09-24 06:20 UTC, OttoAllmendinger commented on ts_src/payments/p2tr.ts
> +    const words = bech32m.toWords(o.output.slice(2));
maybe we should sanity check those two bytes / use the existing methods to validate and parse the script

2021-09-24 06:20 UTC, OttoAllmendinger commented on test/taproot.spec.ts
> +      // example taken from bitcoinops taproot workshop musig exercise
link pls

2021-09-24 10:48 UTC, OttoAllmendinger commented on types/payments/index.d.ts
> +    weights?: number[];
I think you are correct

2021-09-24 10:49 UTC, OttoAllmendinger commented on ts_src/payments/p2tr.ts
> +    const words = bech32m.toWords(o.output.slice(2));
OTOH the other payment builders don't do that either

2021-09-24 13:59 UTC, sangaman commented on test/taproot.spec.ts
> +      // example taken from bitcoinops taproot workshop musig exercise
I'll also note that most of these expected results are derived from the optech taproot workshop example.

2021-09-24 14:10 UTC, sangaman commented on ts_src/payments/p2tr.ts
> +    const words = bech32m.toWords(o.output.slice(2));
The other payment builders do have some "extended validation" logic that I left out for now, I figured it will be easier to implement later and didn't want to get held up by it. I figure validating the first two bytes of the output we're provided makes sense to do there.

Alternatively, since I believe the first two bytes are constant, this builder could only accept the 32 byte output witness program and then add the 2 bytes to create the output script. That makes more sense to me actually since it eliminates the possibility of user error, but might make sense as a followup to this PR. Although I could do it here if it makes sense to everyone.

2021-09-24 14:25 UTC, brandonblack commented on ts_src/taproot.ts
> +    pubkeys.length > 1,
https://github.com/jonasnick/secp256k1-zkp/blob/0aeaa5dfb19445f845890f3a4502c934550f4548/include/secp256k1_musig.h#L200
>         n_pubkeys: length of pubkeys array. Must be greater than 0.

2021-09-24 14:27 UTC, brandonblack commented on ts_src/taproot.ts
> +    const c = bcrypto.sha256(Buffer.concat([L, trimmedPubkey]));
My only concern is that once we've generated any wallets using one version of pubkey aggregation, we're pretty locked in. For that reason, I think we should discuss with (at least) Jonas before we committing to an aggregation scheme.

2021-09-24 19:40 UTC, sangaman commented on ts_src/taproot.ts
> +    pubkeys.length > 1,
It seems really odd to me to want to go through the extra steps of key aggregation for a single key, I don't see any benefit from that. My inclination is still to disallow it here, even if it's technically doable in secp256k1-zkp. It shouldn't break compatibility afaict.

2021-09-24 21:31 UTC, sangaman commented
OK, I went ahead and added the logic for MuSig2*, skipping exponentiation of the second key in the sorted list of keys for key aggregation.

I also got some key aggregation examples directly from the code at https://github.com/jonasnick/secp256k1-zkp/tree/musig2 to test against. In the process I added two new tagged hashes to match the logic there, `KeyAgg list` and `KeyAgg coefficient`. The good news is I was able to get those to pass without too many changes, basically just the MuSig2* and tagged hashes described above.

I resolved the review comments that I thought were addressed pretty straightforwardly by my commits. I think the last step is to get another quick pass on reviews and then clean up the commit history & messages to describe the changes since the original commit.

2021-09-24 21:55 UTC, brandonblack commented on ts_src/taproot.ts
> +};
```suggestion
function makeHashPrefix(tag: Buffer): Buffer {
  return Buffer.concat([tag, tag]);
}

const TAGGED_HASH_PREFIXES = {
  TapLeaf: makeHashPrefix(TAPLEAF_TAGGED_HASH_PREFIX),
  TapBranch: makeHashPrefix(TAPBRANCH_TAGGED_HASH_PREFIX),
  TapTweak: makeHashPrefix(TAPTWEAK_TAGGED_HASH_PREFIX),
  'KeyAgg list': makeHashPrefix(KEYAGG_LIST_TAGGED_HASH_PREFIX),
  'KeyAgg coefficient': makeHashPrefix(KEYAGG_COEFFICIENT_TAGGED_HASH_PREFIX),
};
```

2021-09-24 22:03 UTC, brandonblack commented on ts_src/taproot.ts
> +};
```suggestion
const TAGS = [ 'TapLeaf', 'TapBranch', 'TapTweak', 'KeyAgg list', 'KeyAgg coefficient' ];

const TAGGED_HASH_PREFIXES = Object.fromEntries(TAGS.map(tag => {
    const tagBuf = Buffer.from(tag);
    return [tag, Buffer.concat([tag, tag])];
}));
```

2021-09-24 22:04 UTC, brandonblack commented on ts_src/taproot.ts
> +};
Not sure if typescript compiler will handle this, might need to go to an enumerated type, but I haven't done those yet.

2021-09-24 22:05 UTC, brandonblack commented on ts_src/taproot.ts
> +      const pubkey = Buffer.concat([EVEN_Y_COORD_PREFIX, trimmedPubkey]);
Love this vs. re-trimming like it used to be. Nice.

2021-09-24 22:14 UTC, brandonblack requested changes

2021-09-24 22:14 UTC, brandonblack commented on ts_src/taproot.ts
> +  return aggregatePubkey.slice(1).compare(EVEN_Y_COORD_PREFIX) === 0
I think this should be `.slice(0,1)`, although it might make sense not to branch and just always replace the first byte.

2021-09-24 22:14 UTC, brandonblack commented on ts_src/taproot.ts
> +    : Buffer.concat([EVEN_Y_COORD_PREFIX, trimFirstByte(aggregatePubkey)]);
Can this be replaced with `aggregatePubkey[0] = EVEN_Y_COORD_PREFIX;`?

2021-09-25 15:39 UTC, sangaman commented on ts_src/taproot.ts
> +};
I like this a lot, particularly since this list of tagged hashes is going to keep growing, and it satisfies the type checking if you define `TAGS` with `as const`, but that (and `Object.fromEntries` I believe) requires typescript 3.4+. I'm inclined to just upgrade the version, if upstream doesn't want to do that we can switch back to what I have here currently.

2021-09-25 15:39 UTC, sangaman commented on ts_src/taproot.ts
> +  return aggregatePubkey.slice(1).compare(EVEN_Y_COORD_PREFIX) === 0
Yep thanks for catching this.

2021-09-25 15:47 UTC, sangaman commented on ts_src/taproot.ts
> +    : Buffer.concat([EVEN_Y_COORD_PREFIX, trimFirstByte(aggregatePubkey)]);
Yep makes sense, just skip the `slice` and branch.

2021-09-27 17:27 UTC, brandonblack approved these changes

2021-09-28 16:18 UTC, brandonblack commented on ts_src/taproot.ts
> +    .reduce((prev, curr) => ecc.pointAdd(prev, curr), tweakedPubkeys[0]);
> initialValue Optional
>    A value to which previousValue is initialized the first time the callback is called. If initialValue is specified, that also causes currentValue to be initialized to the first value in the array. If initialValue is not specified, previousValue is initialized to the first value in the array, and currentValue is initialized to the second value in the array.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
This can be simplified to
```suggestion
const aggregatePubkey = tweakedPubkeys.reduce((prev, cur) => ecc.pointAdd(prev, curr));
```

2021-09-28 20:13 UTC, sangaman commented on ts_src/taproot.ts
> +    .reduce((prev, curr) => ecc.pointAdd(prev, curr), tweakedPubkeys[0]);
Yep that checks out, the slice is superfluous.

2021-09-28 20:16 UTC, brandonblack commented on ts_src/taproot.ts
> +    .reduce((prev, curr) => ecc.pointAdd(prev, curr), tweakedPubkeys[0]);
Yeah, I suggested the slice, but I'm a bit rusty still, sorry! :)

2021-09-30 18:37 UTC, tylerlevine approved these changes
awesome work, looks good to me 🚀

2021-09-30 18:37 UTC, tylerlevine commented on ts_src/taproot.ts
> +    const weight = weights ? weights[index] || 1 : 1;
Fine with me. I think now that you've updated the typescript version it should work but no big deal.

2021-09-30 18:37 UTC, tylerlevine commented on ts_src/taproot.ts
> +  // Now that we have a queue of weighted scripts, we begin a loop whereby we
Excellent comments here 👍

2021-09-30 20:46 UTC, sangaman commented on ts_src/taproot.ts
> +    const weight = weights ? weights[index] || 1 : 1;
Indeed you're right, it works now with the newer typescript. I"ll make this change but put it in the commit that upgrades typescript, so if upstream doesn't want to change typescript we can just leave that commit off.

2021-09-30 22:26 UTC, sangaman commented on ts_src/taproot.ts
> +    const weight = weights ? weights[index] || 1 : 1;
Psych, my IDE thinks this syntax is fine, but running `tsc` even with the latest version still craps out on this line. Back to the old way,.

2021-09-30 22:52 UTC, tylerlevine approved these changes

2021-10-03 18:12 UTC, merged